### ISSUE TITLE
Video.js 官方已经是8.6.1 是否可以升级一下nuget吗？

### ISSUE THREAD

**Issue by itchangc** [densen2014/BootstrapBlazor.VideoPlayer#3]
<link href="https://vjs.zencdn.net/8.6.1/video-js.css" rel="stylesheet" />

新版本的 8.6.1 做了浏览器的兼容，现在我使用你封装的  Video.js 7.21.1  浏览器不能播放视频

**Comment by densen2014** [comment]
下一个版本，我留一个外部js路径接口

**Comment by itchangc** [comment]
需要多久会升级，你要是不升级我就自己升级啦，等不急了-

**Comment by densen2014** [comment]
你是什么浏览器和什么环境？

**Comment by densen2014** [comment]
你自己升级测一下，pr进来我合并就好了啊。 开源项目还望大佬多多支持

**Comment by densen2014** [comment]
v 8.0.1
- 修复播放器某些特殊浏览器无法播放的问题, 升级内置播放器版本到 8.6.1
- 添加 VideoJsPath : 自定义video.js路径,默认为null,使用内置video.js
- 添加 LanguagePath : 自定义语言包路径,默认为null,使用内置语言包
