### ISSUE TITLE
嗨，这个播放器mpegts.js可以支持吗

### ISSUE THREAD

**Issue by itchangc** [densen2014/BootstrapBlazor.VideoPlayer#5]
URL地址： https://github.com/xqq/mpegts.js

这个js播放器支持  flv 播放，音视频流媒体对flv支持非常友好。使用率会很高

**Comment by densen2014** [comment]
```
<link href="//path/to/video-js.css" rel="stylesheet">
<script src="//path/to/video.min.js"></script>
<script src="//path/to/flv.min.js"></script>
<script src="//path/to/videojs-flvjs.min.js"></script>
<video id="videojs-flvjs-player" class="video-js vjs-default-skin" controls>
  <source src="movie.flv" type='video/x-flv'>
</video>
<script>
  // Setting the techOrder is necessary in 5.x
  // In 6.x techs are added automatically
  videojs('videojs-flvjs-player', {
    // 5.x only:
    // techOrder: ['html5', 'flvjs']
  });
</script>
```

**Comment by itchangc** [comment]
> ```
> <link href="//path/to/video-js.css" rel="stylesheet">
> <script src="//path/to/video.min.js"></script>
> <script src="//path/to/flv.min.js"></script>
> <script src="//path/to/videojs-flvjs.min.js"></script>
> <video id="videojs-flvjs-player" class="video-js vjs-default-skin" controls>
>   <source src="movie.flv" type='video/x-flv'>
> </video>
> <script>
>   // Setting the techOrder is necessary in 5.x
>   // In 6.x techs are added automatically
>   videojs('videojs-flvjs-player', {
>     // 5.x only:
>     // techOrder: ['html5', 'flvjs']
>   });
> </script>
> ```

没看明白怎么使用

**Comment by itchangc** [comment]
我想使用 nuget 包 BootstrapBlazor.VideoPlayer 
进行播放 flv 的视频，但是BootstrapBlazor.VideoPlayer不支持，你发的 html 代码意思是让我来集成到 BootstrapBlazor.VideoPlayer 组件里吗
